name: .NET Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore RETAIL-STORE-SALES-MANAGEMENT-SYSTEM/StoreManagement.sln

      - name: Build solution
        run: dotnet build RETAIL-STORE-SALES-MANAGEMENT-SYSTEM/StoreManagement.sln --configuration Release

      - name: Publish project
        run: dotnet publish RETAIL-STORE-SALES-MANAGEMENT-SYSTEM/StoreManagement.sln --configuration Release --output ./publish
