name: Build and deploy ASP.Net Core app to Azure Web App - store-management

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build RETAIL-STORE-SALES-MANAGEMENT-SYSTEM/StoreManagement.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish RETAIL-STORE-SALES-MANAGEMENT-SYSTEM/StoreManagement.sln -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B33800D3BE3A436C91BBD791ECF8D723 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D9EB7401388249708917AACCEACE715B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3F46C2ED553D4B4399147A683C2ADE04 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'store-management'
          slot-name: 'Production'
          package: .
